### ISSUE TITLE
Typos and other text issues in case 5

### ISSUE THREAD

**Issue by PhoenixBound** [ScarletStudy/DGS1-3DS-Release#100]
Just finished this game last night. I really enjoyed it. I really want to thank all of you guys who worked on this translation project! That said, I did find a lot of blips that made me look twice at the text, and I took a screenshot whenever that happened. (Disclaimer: I'm an American, but I'm pretty sure most of these issues apply to most varieties of English.)

I saw you respond to another issue with multiple by referring to the numbers, so I numbered the items in this report to make it a little more manageable. There's a lot more items than I remembered. (Surprised that many of these haven't been reported yet... My title screen says 2.4.0, and I don't think there were any hotfix releases?)

---

![Iris: Of course I am! After all, tonight... We're going to have very special guest!](https://user-images.githubusercontent.com/13182187/58765224-2e1ea800-8536-11e9-80c8-b562aca7555c.png)

1 - "very special guest" --> "**a** very special guest"

---

![Naruhodou: (I'm not too sure about bringing a ten year-old girl to a crime scene.)](https://user-images.githubusercontent.com/13182187/58765253-c026b080-8536-11e9-85f9-055ce9f1752a.png)
![Naruhodou: Thank you. I certainly appreciate career advice from a ten year old.](https://user-images.githubusercontent.com/13182187/58765308-6f638780-8537-11e9-9e1a-877f1b8025c5.png)

2 - I think ten-year-old in both of these contexts should have two hyphens? The first one definitely needs to be changed.

---

![Naruhodou: This is just something I've been wondering about personally for awhile now, but...](https://user-images.githubusercontent.com/13182187/58765372-04668080-8538-11e9-89a9-edc8134c3c2b.png)

3 - "for awhile" --> "for a while" or just "awhile" without the for.

---

![Gregson: For goodness sake. She has some nerve to use an inspector as a messenger.](https://user-images.githubusercontent.com/13182187/58765409-6c1ccb80-8538-11e9-80d2-740bf2a15e19.png)

4 - "For goodness sake" --> "For goodness' sake" (missing apostrophe)

---

![Great British Empire](https://user-images.githubusercontent.com/13182187/58765436-b140fd80-8538-11e9-8e65-8e750e20a105.png)

5 - This is more a question than a correction. Is "Great British" a common thing in English? I get that it's "Great Britain" and this game is called "The Great Ace Attorney," but in the Social Studies classes I've taken, it's usually called the "British Empire." I remember in the first patch it was only "Great British" everywhere, but then it began to intersperse it with normal "British" in a few places after the case 3+4 patch.

---

![Juror 3: The New World should seize everything stereoscopically, just like this!](https://user-images.githubusercontent.com/13182187/58765587-3b3d9600-853a-11e9-8a95-fddb3f244d25.png)

6 - Putting aside this guy's [amazingness](https://user-images.githubusercontent.com/13182187/58765890-8c9b5480-853d-11e9-8a1b-faa97314cd67.png)... He's randomly talking about the "New World" in capital letters, which normally means the Americas. That probably wasn't intended? From context this line is more like how everyone's talking about the new *century*. There's probably a better way to rewrite that than "century," but I can't think of it now in the moment.

---

![Judge: I trust you were listening carefully to his closing argument?](https://user-images.githubusercontent.com/13182187/58765700-61176a80-853b-11e9-9dc1-21558be6d6ec.png)

7 - From what I remember, the last line occurs after the screen faded in from black. It felt a little awkward having the judge say that line because it feels like he's continuing after first addressing someone, which he didn't do. Maybe it could use a "Now then" at the beginning or something, or saying "Witnesses" again before he starts?

---

![Hatch's Pawnbrokers](https://user-images.githubusercontent.com/13182187/58765764-f61a6380-853b-11e9-8f31-6d4056a6ace7.png)

8 - Every time "pawnbrokers" was used to refer to a shop felt strange. "Pawnbrokers" means "more than one pawnbroker," where a pawnbroker is a person. To refer to a pawnbroker's shop, it would be "pawnbroker's" with an apostrophe, but that doesn't really look good when it's talking specifically about one named shop.

I'm not 100% sure about the right way, but here's what feels right:
* When it's not a proper noun, like "dropping a pledge off at the pawnbroker's," just replacing it with an apostrophe should probably be fine
* When it's used as the name of Hatch's shop, make it something else like "Hatch's Pawnshop"

---

![Chrogray: I never denied that, now, have I?](https://user-images.githubusercontent.com/13182187/58765897-a76dc900-853d-11e9-8889-4816ba1d9300.png)

9 - "now, have I?" --> "now, did I?"

---

![Chrogray: I can guarantee that the coat is soiled by his (Hatch's) blood!](https://user-images.githubusercontent.com/13182187/58765939-26630180-853e-11e9-9a53-52f100d81e40.png)

10 - Chrogray is referring to Hatch's blood here, not Mortar's. Since Naruhodou is agreeing even though he knows it's actually Mortar's blood, "soiled by his blood" --> "soiled with blood" or similar.

---

![van Zieks: The British government will no doubt issue a formal complaint against your country.](https://user-images.githubusercontent.com/13182187/58765999-126bcf80-853f-11e9-9ee1-b872fbd2fa4b.png)

11 - Another one that's more a question than a clear error (IANAL, maybe what you already have is the correct legal terminology). "Against" Naruhodou's country... that means Great Britain is complaining about Japan to a higher authority? If it's not that, then "to" makes a bit more sense, to me at least (Great Britain is complaining about Naruhodou to Japan).

---

![Chrogray: Know that your accusations do not phase me.](https://user-images.githubusercontent.com/13182187/58766035-a473d800-853f-11e9-95f2-cddfe0e6d6bc.png)

12 - "phase" --> "faze"

---

![Chrogray: I resolved myself to study as hard as I could. All so I could escape from that life.](https://user-images.githubusercontent.com/13182187/58766043-ba819880-853f-11e9-9407-bf39a5239cab.png)

13 - The "myself" in there sounds awkward as an intensive pronoun, and it's grammatically incorrect for it to be a reflexive pronoun ("resolve" in this sense doesn't take a direct object), so it could be removed.

---

![Chrogray: I... I ended the Devil's life with my own hands!](https://user-images.githubusercontent.com/13182187/58766093-69be6f80-8540-11e9-982b-e261cf2da676.png)

14 - "The Devil" with a capital D refers to the religious figure specifically. I think this shows up in a few other places, too.
"Devil" --> "devil," at least here.

---

![van Zieks: You called Megundal "The Devil".](https://user-images.githubusercontent.com/13182187/58766107-7e026c80-8540-11e9-85f1-cfccc3211d93.png)

15 - Related to the above. Even if you end up keeping the capital-D spelling in 14, it's best to make "the" lowercase.

---

![Naruhodou: You Susato Tossed me to the other side of the room.](https://user-images.githubusercontent.com/13182187/58766285-514f5480-8542-11e9-87e2-42022b2f923a.png)

16 - Since "Susato Toss" is being used as a verb, it would be clearer to read if it was hyphenated. (When I originally took this screenshot, I forgot the Susato Toss was a thing and thought, "How did this outrageous capitalization get through?!" Then I realized better while making this report.)

---

![Naruhodou: Huh? Wha?](https://user-images.githubusercontent.com/13182187/58766313-ad19dd80-8542-11e9-9793-578af98e7265.png)
![Naruhodou: Huh? Wha? Umm?](https://user-images.githubusercontent.com/13182187/58766319-b6a34580-8542-11e9-9e40-0b3e8b4695cb.png)

17 - I missed parts of the anime cutscene subtitles, but they're probably fine. Now. Finally, we get to the classic Ace Attorney ending gag. It's... translated very naturally. I like how it sounds, nice job to whoever figured out this phrasing.

But I was curious to see if it matched other Ace Attorney endings, in which the lawyer just says "Huh? Huh? Huh?" over and over. It looks like it does match (I checked AA3 and this game; they both use え。 repeated many times). I would link videos to compare, but YouTube is down for me right now.

"Huh? Wha? Umm?" --> "Huh? Huh? Huh?"

---

![Holmes: They've (music boxes have) been flying off the shelves! What ever happened to real detective work?!](https://user-images.githubusercontent.com/13182187/58766497-04b94880-8545-11e9-90de-167c9caa6e7e.png)

18 - Credits scene time. He can't really say they're flying off the shelves, because he's *getting* more of them, not selling a lot of them or giving them away--as far as he's mentioned, at least. I don't remember the entire context of this, so I can't suggest a more natural line or phrase.

---

...That's everything I found that seemed strange. Thank you all again for working on this game translation, it turned out pretty amazing and mind-blowing. I got a DGS 2 cartridge at the beginning of the year, and I'm looking forward to your translation of that game.

**Comment by keksdee** [comment]
For some reason I felt like responding to this issue right away while I procrastinate and leave all the others to rot.... I'll get to them soon, I swear. Anyway,

1. Yeah, that was a typo. It's been fixed by now, fortunately.
2. Ah fuck, probably my bad there. That'll go in the "fix" pile as I eventually get around to looking up the proper style.
3. I'm tempted to call this a typo. Thanks, fix pile
4. WHOOPS, fix pile
5. In this specific case, I think we went with "great" because Vortex is very very proud of his country. But yeah, as you noticed, we culled a lot of the "Greats" a while back.
6. Agree, fix pile
7. Fair enough, fix pile
8. Agree, fix pile
9. I think this is a case of someone making a modification and then forgetting to fix the grammar. I hope it wasn't me... fix pile
10. Fair enough, fix pile
11. Fair enough, fix pile
12. I swear I looked this up before and found the opposite wtf, fix pile
13. Sure, fix pile
14. I'll think about it™
15. I don't know what evem happened with this line in general, fix pile
16. I'll think about it™
17. Eugh. This one's my bad I guess, someone else in the group mentioned it to me and I was like "nah that's totally not it, this looks better," but having a second person say it means I should probably put it back. Thanks, fix pile
18. Disagree here tho, "flying off the shelves" as in people are buying them up just to send to him. If that's not clear enough then maybe I could think about™ fixing it up a bit. Re-timing it is going to be a pain though /whine

Thanks fam
