### ISSUE TITLE
Case 4: Second Closing Argument

### ISSUE THREAD

**Issue by Trueblade1017** [ScarletStudy/DGS1-3DS-Release#101]
During the second closing argument, I pressed Juror 6's statement and it changed accordingly.  Then when I tried to clash Juror 3 and select Juror 6 (from 3DS bottom screen), the text for Juror 6 shows the original statement instead.  Luckily, the game still considers this to be correct.

This is the updated statement:

![IMG_0431](https://user-images.githubusercontent.com/51686625/59238999-14343380-8bce-11e9-808e-b8ce202a62f4.jpg)

![IMG_0430](https://user-images.githubusercontent.com/51686625/59239145-902e7b80-8bce-11e9-8a5d-92d4161d0516.jpg)

**Comment by keksdee** [comment]
NOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO

Fixed, thanks

GOD
