### ISSUE TITLE
Typos and other text issues

### ISSUE THREAD

**Issue by ACE134** [ScarletStudy/DGS1-3DS-Release#104]
I wanted to thank you for your efforts for translating the game and making it happen, splendid work!

I found some typos (My English isn't that good so I might not get it right, but I thought of sharing it to make sure (Both in final episode):

1. 
![photo_2019-07-09_18-18-29](https://user-images.githubusercontent.com/52711125/60901519-c5ce8f00-a276-11e9-92c8-637a5b53879d.jpg)

"I TOLD you they'd agree" was a bit weird, because the reaction from Susato & Naruhodo was getting surprised as if they're disagreeing. Maybe she meant the fans who'll send the music boxes that they're agreeing to it, but that wasn't mentioned until the ending credits.

"I TOLD you they'd agree" --> "I TOLD you they'd disagree"

2.
![photo_2019-07-09_18-19-21](https://user-images.githubusercontent.com/52711125/60901794-3c6b8c80-a277-11e9-98b1-ae87e5884c7c.jpg)

"...Then when-" I guess it's "Than" because "Then" felt like it doesn't make sense.

"...Then" -->"...Than"

----------------------------------------------------------------------

As for text issues, I'm using Citra emulator so there's a chance it's the problem, but anyway I noticed that the Backlog at the end of "Theatre of Logic & Reason" has some issue, it doesn't show any text, only a big blank space:

![animation](https://user-images.githubusercontent.com/52711125/60902981-3a0a3200-a279-11e9-93c5-dc4971676870.gif)

![animation (2)](https://user-images.githubusercontent.com/52711125/60903031-4db59880-a279-11e9-8eae-4973bfc1ac6f.gif)

Thank you so much again. As for the reason I'm using Citra over hacked 3DS, it's because I'm not that good at hacking & I'm afraid if any problems occur to the 3DS.

**Comment by Wendy-Youngbag** [comment]
1. This is fine as Iris is referring to Susato and Naru agreeing with her thinking Holmes is going over the top.

2. Thank you - this has already been fixed :)

3. This is a Capcom issue that we know and happens with DD and SoJ too - so nothing really to do with us
