### ISSUE TITLE
Ep. 5, Investigation 1: Some missing backlog text in the 1st "Theatre of Logic" scenario 

### ISSUE THREAD

**Issue by arizvisa** [ScarletStudy/DGS1-3DS-Release#106]
Thanks for taking the time to do all the work to get this translated for us. This issue isn't too important or anything and as a result is not too necessary to prioritize, but it seems like the text for some of the backlog is missing near the beginning of this particular scenario.

The scenario is in Hatch's Pawn Shop after discovering the sketch for Gina Lestrade in the "Egg Benedict" character's hand.  I included the text that encompasses it and the space that's available. Hopefully that helps with locating it.

```
Susato:
    W-What does it say?

Naruhodou:
    It says...

    "Name: Gina Lestrade. Height: Five feet,
    two inches."

    "Distinctive old green hat and waistcoat.
    Wears an old blue bag and old white shirt."

    These are all of Gina's identifying features!

Susato:
    What on earth?!

Naruhodou:
    <missing -- appears as 6-7 lines worth of space>
 
Susato:
    <missing -- appears as 35ish lines worth of space>

Naruhodou:
    Just a moment ago, you claimed...

    ...That you chased Gina to this shop after she
    stole your pledge ticket.

Holms:
    But I'm pleased to see that your claim was nothing but lies.
```

**Comment by PixelSergey** [comment]
This is a known issue that occurs with the game engine itself, as opposed to the translation. It also appears sometimes in Dual Destinies and Spirit of Justice.

**Comment by arizvisa** [comment]
Ah, ok. Good to know.

Is there another issue number I should reference this to for tracking so I can close this? Or should I just close this as it's not something that you guys are able to fix w/o some dev effort?

**Comment by PixelSergey** [comment]
For now, it seems to be the latter. Fixing this would require fixing Capcom's own engine, something that isn't a very fun or easy task to do.

**Comment by arizvisa** [comment]
kk. sounds about right. Thx!
