### ISSUE TITLE
Small typo in chapter 3 Vortex dialogue menu

### ISSUE THREAD

**Issue by herrnici** [ScarletStudy/DGS1-3DS-Release#111]
At the very beginning of the chapter, in the conversation with Lord Vortex, the dialogue option label 'The exchange programme' is cut off:

![grafik](https://user-images.githubusercontent.com/1701578/69500544-74a8fa00-0efc-11ea-9810-83f48a37a6ee.png)

**Comment by Wendy-Youngbag** [comment]
Thanks - this comes from differences in spellings between American English and British English, the former using "program" and the latter "programme." This has been fixed internally now.
