### ISSUE TITLE
"They" instead of "There"

### ISSUE THREAD

**Issue by Nama** [ScarletStudy/DGS1-3DS-Release#112]
Hi,
I'm amazed how professional this is. I wouldn't notice that this is a fan translation :O

I have the Version 2.4.1 and noticed this. "They" should be "There" if I'm not wrong.
![top_0000](https://user-images.githubusercontent.com/2297270/71539615-25147e80-293f-11ea-9365-ff1bbf59cac6.jpg)

**Comment by Wendy-Youngbag** [comment]
Hi, thanks for your comment!

 In this case, Holmes is referring to an earlier line by Naruhodou where he asks about these truths, so using "they" is correct.
