### ISSUE TITLE
problem with installing

### ISSUE THREAD

**Issue by rsefaqt** [ScarletStudy/DGS1-3DS-Release#113]
First I'm thankful for the English patch of DGS! I'm trying with nintendo 3DS. I success to check the Great Attorney Logo on the top screen after choosing DGS1-patcher. Than the screen prints out problems and patch is not installed when I check in launch FBI. There's only blank folder named DGS in SD:/3ds/ scarletstudy 

it says

V:/autorun.gm9
line 34: label not found
goto dgsnotfound

how can I solve this problem?

**Comment by wabberz** [comment]
Is a DGS Game Card inserted or the eShop version installed? The patcher only works if you already have the original game.

**Comment by rsefaqt** [comment]
Yes I use game card.
But I use custom firmwared nintendo to apply patch, is that would be problem??

**Comment by wabberz** [comment]
You couldn't boot the patcher without the custom firmware. Can you play the original game from the game card?

**Comment by rsefaqt** [comment]
oh I have the custom firmware! What would be a problem then??

**Comment by wabberz** [comment]
Very hard to tell. Which CFW do you have set up? Luma3DS? Which version?

**Comment by rsefaqt** [comment]
Yes. How can I check the version?

**Comment by rsefaqt** [comment]
Also I got game file too

**Comment by wabberz** [comment]
> Yes. How can I check the version?
Hold SELECT while turning on your 3DS. The version should be in the first line on the top screen, the last line on the bottom screen should say which mode it was booted in.

> Also I got game file too
Not sure what you mean by that? Your Game Card?

**Comment by rsefaqt** [comment]
My version is luma 3ds 9.1
And I got game file to!

**Comment by wabberz** [comment]
What do you mean with "game file"? I thought you have a Game Card? What's a "game file"?

**Comment by rsefaqt** [comment]
Oh ‘game file’ is not a ‘.cia’ file in sd card??

**Comment by wabberz** [comment]
I have no idea what you mean by that. You said you have the physical Game Card? Well, do you, or do you not?

**Comment by rsefaqt** [comment]
I have only sd card but I have the game by installing cia file. I could fine DGS app on the start page

**Comment by wabberz** [comment]
Sorry, we don't support piracy. You're on your own.

**Comment by rsefaqt** [comment]
Okay thank you
