### ISSUE TITLE
Cannot transfer patch/firm files via microSD management software (SMB server)

### ISSUE THREAD

**Issue by ryotoko** [ScarletStudy/DGS1-3DS-Release#119]
### About your device

**Which 3DS model are you using?** (Old/New 2DS/3DS)
New 3DS
**Which Luma3DS version are you running?** (hold SELECT on boot to check)
10.2
**Which 3DS firmware version are you running?** (open System Settings to check)
11.13
**Which version of our patch are you running?** (should be visible on the top right of the title screen)
2.4.1
### Your issue

**Please describe the issue you are experiencing:**
This is just kind of bizarre, but I was not able to transfer the files or folders extracted from your 7z file via the N3DS's microSD management app. I was getting a permission denied or missing file error. 

Are there some kind of weird access permissions set on these files? I successfully managed to do it by opening them in a hex editor and creating a file copy. Creating a copy in Windows Explorer led to the same error. No other files or folders unrelated to your project give this error, whether they originate from a 7z file or not.

If you're actively preventing transfer by this method, you should state as such because I was pulling my hair out trying to figure out what was wrong. I routinely transfer files to my N3DS this way.

**Comment by wabberz** [comment]
We do not. I have no idea what cause this issue, but this is unrelated to our project. Closing.

**Comment by ryotoko** [comment]
> 
> 
> We do not. I have no idea what cause this issue, but this is unrelated to our project. Closing.

I'm sorry but **_it is_** related to your project, as it has to do with the attributes you've set on the files and folders you are distributing.

Upon further research, I can confirm that your files and folders are being flagged with the X, P and U attributes. P and U are actually mutually exclusive attributes, and none of these have any business being on any of the files or folders that you're distributing. Removing theses attributes from your files and folders fixes the problem. 
![Capture](https://user-images.githubusercontent.com/68757712/88441891-6848aa00-cdc7-11ea-881d-dc4292554a19.PNG)


This problem is reproducible, I've done it on another N3DS system on another PC.

**Comment by wabberz** [comment]
I don't think it is. Using 7-zip 20.00 alpha I get this:
![image](https://user-images.githubusercontent.com/22555393/88446998-163b6f00-ce2f-11ea-8593-dfea73089941.png)

You can correct me on this, but I'm pretty sure the 7z container format doesn't even support these new extended attributes. They are not set in the archive, anyways. **It was created on a Linux system that does not support these attributes.**

I assume you're either using some other application (could also be your browser that flags the download) to extract that applies the attributes or something else on your system(s) interferes. In any case, this is not related to this project.
