### ISSUE TITLE
An error occurred(ErrDisp)

### ISSUE THREAD

**Issue by joshus215** [ScarletStudy/DGS1-3DS-Release#121]
[](https://gyazo.com/966fec7d3e3e1ff0b8f45d16f248706c) ### About your device

**Which 3DS model are you using?** (Old/New 2DS/3DS)

**Which Luma3DS version are you running?** (hold SELECT on boot to check)

**Which 3DS firmware version are you running?** (open System Settings to check)

**Which version of our patch are you running?** (should be visible on the top right of the title screen)

### Your issue

_In case of a crash, please attach the corresponding crashdump (likely the newest file in `sd:/luma/dumps/arm11/`)_

**Please describe the issue you are experiencing:**

**Comment by wabberz** [comment]
empty report. closing.
