### ISSUE TITLE
Minor typo 

### ISSUE THREAD

**Issue by Da-KinGanondorf** [ScarletStudy/DGS1-3DS-Release#124]
### Location

**Which Episode?** (1-5)

**Are you running the latest version of our patch?**

### Please describe the issue
Episode 4 the clouded kokoro trial 1 starts off with the prosecution saying they are ready and then the defense saying the "defence" is ready

**Comment by Da-KinGanondorf** [comment]
Oh I realize I forgot to mention I am on the newest update as of January 27th

**Comment by Wendy-Youngbag** [comment]
The translation is in British English, where "defence" is the preferred spelling.

**Comment by Da-KinGanondorf** [comment]
If that's the case then the three other times that the word was used in the same section of the game were misspelled instead

**Comment by Da-KinGanondorf** [comment]
The reason it caught me off is because I read it spelled both ways multiple times

**Comment by Da-KinGanondorf** [comment]
Also apparently depending on the suffix added to the word even the british spell it with an s specifically when a suffix starting with the letter I.

**Comment by Wendy-Youngbag** [comment]
I have searched through the script but there are no instances of "defense". If you have a screenshot to show where, it would be most appreciated.

I am British, and many of the team members are British. We spell it as "defence". The "ise" suffix is a different matter entirely (for words such as "specialise" or "normalise".)
