### ISSUE TITLE
Typo speaking to Hatch (Ep. 5)

### ISSUE THREAD

**Issue by bclamb2** [ScarletStudy/DGS1-3DS-Release#127]
![IMG_0585](https://user-images.githubusercontent.com/77414635/113521245-10b12f80-954d-11eb-860c-419cad718279.jpg)

Occurs when talking to Hatch about Gina.

**Comment by wabberz** [comment]
Help me out here, I don't see the typo.

**Comment by bclamb2** [comment]
Hatch says "many a suspicious item," however you can't use the adjective (many) to describe the noun (item) due to item being a singular noun. This can be resolved by changing the sentence to "She has brought in many suspicious items." -for several items- or "She has brought in a suspicious item." -for a single item.-

**Comment by wabberz** [comment]
https://www.merriam-webster.com/dictionary/many%20a%2Fan

**Comment by bclamb2** [comment]
Oh wait it's actually a phrase people use. Sorry I guess this was a false alarm.
