### ISSUE TITLE
Chapter 1 Trial 1-3

### ISSUE THREAD

**Issue by fulyflea** [ScarletStudy/DGS1-3DS-Release#23]
Extra spacing at the beginning of the sentence.
![img_1495](https://user-images.githubusercontent.com/35005061/34550740-358d2724-f14e-11e7-98a1-9f0a5ccfb7e6.jpg)
Double spacing.
![img_1496](https://user-images.githubusercontent.com/35005061/34550745-3eced92c-f14e-11e7-9a59-c06a3226fdb6.jpg)
Naruhodou asked a question and Hosonaga answered 'extraterritorial rights' to him. After that Naruhodou asked Hosonaga about the meaning of 'British consular courts' when it should be about 'extraterritorial rights'.
![img_1498](https://user-images.githubusercontent.com/35005061/34550754-535d1890-f14e-11e7-918c-30bd79c82756.jpg)
![img_1499](https://user-images.githubusercontent.com/35005061/34550755-53908162-f14e-11e7-8531-a55cec217224.jpg)

Also in the manual, Phoenix's 's' is missing.
![img_1484](https://user-images.githubusercontent.com/35005061/34550990-7c02547a-f150-11e7-9b73-41fd06b4589d.JPG)

**Comment by rltruong** [comment]
![img_0184](https://user-images.githubusercontent.com/20199966/35054158-c340fdcc-fb60-11e7-9810-0103993a7730.JPG)

There's an extra word ("thing") here, after "shocking."

**Comment by Planetbox77** [comment]
I mean, the "thing" that should be removed is the one BEFORE "shocking", because "the only thing 'shocking' here" sounds kinda weird IMO.

**Comment by rltruong** [comment]
@Planetbox77 Now that you mention it, I think removal of either instance is fine. Removal of the instance that happens before "shocking" makes the sentence flow more nicely. But I also think removal of the instance after works, because I read the sentence as 

`"The only thing (that is) "shocking" here is your abnormal obsession with the beefsteak!"`
 
even if the words "that" and "is" are omitted.

**Comment by nabithahmed** [comment]
A small thing I'd like to point out in this picture: 
![](https://user-images.githubusercontent.com/35005061/34550745-3eced92c-f14e-11e7-9a59-c06a3226fdb6.jpg)
Maybe change the "Very literally" to "Quite literally"? I feel this gives the character the sophistication that he himself is portraying.
