### ISSUE TITLE
Chapter 1 Trial 1-2

### ISSUE THREAD

**Issue by fulyflea** [ScarletStudy/DGS1-3DS-Release#24]
When the wrong statement/evidence is chosen, "witness's" -> witness' 
![img_1505](https://user-images.githubusercontent.com/35005061/34574116-66ffbff2-f1b1-11e7-97f1-6d58f192b31a.jpg)

Following what Auchi said, Naruhodou should be thinking about "desperate" and not "confusion and anguish".
![img_1507](https://user-images.githubusercontent.com/35005061/34572799-4b6d4ca4-f1ad-11e7-8da5-739144a913da.jpg)
![img_1506](https://user-images.githubusercontent.com/35005061/34572819-54838d3a-f1ad-11e7-8a0c-9e68f9f91bf6.jpg)

Perhaps it would be better...

if lower case is used when connecting sentences?
![img_1514](https://user-images.githubusercontent.com/35005061/34573107-348967c4-f1ae-11e7-8a17-cf09fab53ace.jpg)
![img_1515](https://user-images.githubusercontent.com/35005061/34573110-34f4bace-f1ae-11e7-8f43-63158d5c9807.jpg)

I can't help but think that this sentence is weirdly structured...? (Final cross examination, press 2nd statement)
![img_1517](https://user-images.githubusercontent.com/35005061/34573516-6bc4e190-f1af-11e7-87dc-f441fa759c96.jpg)

'mine own words' -> my own words
![img_1519](https://user-images.githubusercontent.com/35005061/34573936-dd7467b0-f1b0-11e7-8d1e-d5c6de84b5aa.jpg)

Pardon my lack of history knowledge, but which Powers are you referring to...?
![img_1520](https://user-images.githubusercontent.com/35005061/34573937-ddbacef8-f1b0-11e7-885a-babc37752e5e.jpg)

**Comment by Planetbox77** [comment]
Technically "witness's" also works. There's really no "correct" way to make a common word ending in s possessive, so either one would work here.

However, it is a good idea to keep it consistent. So if using just an apotrophe is more common in the patch, it should probably be changed to "witness'"

**Comment by nabithahmed** [comment]
The sentence "When I carried the beefsteak over, as for whether the professor had drank any water..." could be corrected to "As for whether the professor had _drunk_ any water when I carried the beefsteak over..."
