### ISSUE TITLE
Typos, inconsistencies and minor grammar issues

### ISSUE THREAD

**Issue by nabithahmed** [ScarletStudy/DGS1-3DS-Release#29]
First off, I'd like to thank you guys for the hard work you've put into the translation. Picking this series up was the best investment ever and I really enjoyed playing the 2 episodes so far :)

![photo_2018-02-07_15-24-23](https://user-images.githubusercontent.com/25128143/35974479-1bbd5170-0cfb-11e8-9868-01add6e604e9.jpg)
This little bit said by Naruhodou in 1-1 sounds a bit oddly worded. Wouldn't it be "I'm scared _of_ what will happen?"

![photo_2018-02-07_15-23-58](https://user-images.githubusercontent.com/25128143/35974591-7b7ce206-0cfb-11e8-8f78-3a8c0b4e520a.jpg)
I believe this is in 1-2; Naruhodou says that the victim "bled to death after receiving a single **bullet**." This may be the old-fashioned way of referring to it, or maybe that is an actual way of saying it, I'm not sure. Again, it sounds odd which is why I've pointed it out. Shouldn't it be "bled to death after receiving a single _gunshot_"?

![photo_2018-02-07_15-23-40](https://user-images.githubusercontent.com/25128143/35974861-7aee30e6-0cfc-11e8-9c61-c833a9125347.jpg)
In 1-3, I believe, Brett says "**Magnamious**." A little typo that should be "magnanimous." Also, it's a bit odd that words are capitalized following an ellipsis.

![photo_2018-02-07_15-23-12](https://user-images.githubusercontent.com/25128143/35974993-03059212-0cfd-11e8-969c-3052ed3f092f.jpg)
This is also in 1-3, I think. The judge says that "other than this **bullet**, there **exists** no other means for the murder." when the picture shows the pistol. The sentence is also grammatically incorrect: exists --> exist is the correct usage of the verb. So I would suggest the sentence to be corrected to "Other than this _pistol_, no other means for the murder exist."

And now onto episode 2 (real talk tho, this episode is... SO GOOD) It was also at this point that I realized I could take screenshots via Rosalina, so I apologize for the potato quality of the previous pictures.

![2018-02-06_13-35-53 664_top](https://user-images.githubusercontent.com/25128143/35976018-86343ae6-0d00-11e8-9463-aa362967da45.png)
An odd bit of wording here in 2-1; Naruhodou says "That I'm **an**, uh, Russian [...]" which is incorrect. The filler (uh) doesn't count, so **an** should be _a_, instead.

![2018-02-06_13-44-28 082_bot](https://user-images.githubusercontent.com/25128143/35976235-52a640f6-0d01-11e8-807d-b69c06931736.png) ![2018-02-06_15-19-27 629_top](https://user-images.githubusercontent.com/25128143/35976236-52dd01a4-0d01-11e8-8511-236817f98f16.png)
![2018-02-06_16-02-01 546_top](https://user-images.githubusercontent.com/25128143/35976237-53100c8e-0d01-11e8-8a7d-1003b2f527e9.png)
Inconsistency throughout the entire episode: the group is named in three different ways. (troupe, school, company) The newspaper headline is also inconsistent. This could all just be rephrasing done by the characters themselves, but I've pointed it out, in case that isn't the reason.

![2018-02-06_17-22-14 911_top](https://user-images.githubusercontent.com/25128143/35976629-890f6ac2-0d02-11e8-9753-a75b3cd2b0f9.png) ![2018-02-06_18-43-24 331_top](https://user-images.githubusercontent.com/25128143/35976630-894402f0-0d02-11e8-8e4c-81cd9bb91d3f.png)
Another little typo is Nikomina's last name. Borschevic or Borschevich? I guess it depends on whichever one sounds more old-fashioned.

![2018-02-06_18-49-02 493_top](https://user-images.githubusercontent.com/25128143/35976810-11ef8e4e-0d03-11e8-9467-6c577fbd9cbf.png)
An inconsistency here is that the full form of Mister is written, (Miss was also used in full in some places.) I might be misremembering, but there was an instance when the short form was used, so for consistency, I'd suggest using one way throughout the translation. Another such inconsistency referred to here in issue #24 is apostrophe usage.
![2018-02-06_17-57-03 541_top](https://user-images.githubusercontent.com/25128143/35976983-9d482c30-0d03-11e8-836d-b5edde15f476.png)
The converse is true for this instance in episode 1, mentioned in the above issue, "the **witness's** testimony" and in episode 2, "**Holmes'**"

![2018-02-06_19-16-59 012_top](https://user-images.githubusercontent.com/25128143/35977163-178562b0-0d04-11e8-8e8b-029c9e4d6d6c.png)
The last one I noticed was this. In a previous line, the quoted sentence was much different from what is mentioned here. (I don't have a shot of that, sorry, hehe) Again, this could be a case of rephrasing by the characters,

Hope this helps. I'm not a native speaker, so, any changes I've suggested may be incorrect, and if that is the case, then I'm very sorry. Hehe. Again, I cannot thank you all enough for taking up the translation of this fantastic game. I'll be waiting for that 3rd episode :)))))))

**Comment by Hyarion-SS** [comment]
Thanks for the detailed report. We definitely appreciate it.

**Comment by wabberz** [comment]
@nabithahmed can we reach you somehow?

**Comment by nabithahmed** [comment]
I have a Discord @nabithahmed#9635 :)
