### ISSUE TITLE
Possible error with Vortex's profile

### ISSUE THREAD

**Issue by GoldChimera** [ScarletStudy/DGS1-3DS-Release#34]
Hart Vortex's profile calls him "Lord Chief Justice of England and Wales", even though "and Wales" had not yet been added to the title at the time that the game is set - I don't know whether "and Wales" is present in the Japanese version or if it was erroneously added in translation but if it's the latter it probably wants fixing.

**Comment by Hyarion-SS** [comment]
Quite right. I've slipped it into v2.3.0.2.
