### ISSUE TITLE
Typo in Case 4

### ISSUE THREAD

**Issue by GoldChimera** [ScarletStudy/DGS1-3DS-Release#36]
There's several mentions of the "gas metre", etc, in Souseki's room. I assume the spelling of meter has been changed to comply with UK spellings, but actually the "metre" spelling only applies to the measure of distance - in this case, it should still be a gas "meter".

**Comment by Hyarion-SS** [comment]
Thanks. This has been fixed for the upcoming 2.3.1.

**Comment by szymbar15** [comment]
There's yet another one in case 4 I'm pretty confident about - second Closing Argument has a typo in Juror 6's Pressing statement about celebrating his 75th birthday, I've advanced the text forward that part and the statement had been changed after pressing, but I do believe it was something among the lines of Susato mentioning that putting candles on a cake is a common "practise" in London, which is a typo - I think the correct form should be "practice" instead and practise is only a verb in English language.

**Comment by Hyarion-SS** [comment]
You are correct -- it was even in our style guide, but I'm afraid our spellchecker was never updated to match.

All instances of practise being used as a noun have been fixed.

**Comment by Hyarion-SS** [comment]
Fixed in 2.3.1.
