### ISSUE TITLE
Save File Name suggestion

### ISSUE THREAD

**Issue by CatDonkey** [ScarletStudy/DGS1-3DS-Release#38]
I play the game on and off quite a bit so I often use the save files pretty often. Looking back at the officially released AA games that were localized I find that the save file names in this translation seem a bit off compared to the others, i.e. "Trial 2" during Episode 1. Where the older games would say something like "Trial, Day 1". and seeing how DGS1 only has 1 day of both trials and investigations, I think it would look a lot better if the save files read like "Trial, Pt. 1" or "Investigation, Pt. 1" instead of "Trial 1" or Investigation 1". Sure that might be how it read in the Japanese version, but I strongly feel that it would add some slight consistency between other English versions of the Ace Attorney series as well as make it look a bit better. 

Thanks for all the work all of you have done for this community!
-CatDonkey

**Comment by Hyarion-SS** [comment]
While a good thought, this would currently cause some save file names to overflow on the 3DS.

That said, this is the kind of attention to detail I like, so I'll put some extra effort into trying to make it work sometime.

**Comment by CatDonkey** [comment]
You could also do it like "Invest. - Pt. 1" which is how DD and SoJ had them
![screenshot_20181003-123641_aattorneydd](https://user-images.githubusercontent.com/43726329/46428481-b891dc00-c709-11e8-884f-452af4950f9d.jpg)
