### ISSUE TITLE
Uzukumaru's Breakdown's Audio Lags behind

### ISSUE THREAD

**Issue by thegreatrazz** [ScarletStudy/DGS1-3DS-Release#39]
In Episode 1, the audio for Uzukumaru's breakdown falls ever so slightly behind the visuals.

**Comment by Hyarion-SS** [comment]
This was noticed and tweaked a few days ago. It should be fixed in 2.3.1.

**Comment by Hyarion-SS** [comment]
Fixed in 2.3.1.
