### ISSUE TITLE
Discrepancy in evidence of Chapter 3

### ISSUE THREAD

**Issue by Dormanil** [ScarletStudy/DGS1-3DS-Release#40]
Both witnesses state that the victim was stabbed in the gut. The autopsy report's abstract and the crime scene photo's description state the victim was stabbed in the chest. The details for the autopsy report state that he was stabbed in the abdomen. The crime scene photo itself also clearly shows the wound to be located in the abdomen. Considering that the chest is defined as the area between neck and abdomen, this feels more contradictory than the game would allow.

**Comment by Hyarion-SS** [comment]
Fixed for the next update.
