### ISSUE TITLE
Receipt in Case 4

### ISSUE THREAD

**Issue by Dormanil** [ScarletStudy/DGS1-3DS-Release#41]
The image of Natsume Sousuke's receipt shows different translations of the titles bought:

Zieks <-> Receipt  
A Portrait of Monsieur Lecoq <-> Monsieur Lecoq  
Canterbury Yearning <-> The Canterbury Tales  
Gaboriau and the Sea <-> 20,000 Leagues Under the Sea

Unlike Zieks states, these titles have *not* matched the receipt exactly.

**Comment by Hyarion-SS** [comment]
Fixed for the next update.
