### ISSUE TITLE
LayeredFS

### ISSUE THREAD

**Issue by jorgev259** [ScarletStudy/DGS1-3DS-Release#45]
The patcher is great and all and very user friendly. But is there any chance we could get layeredfs compatible releases?

**Comment by wabberz** [comment]
But it's also a big source for potential issues, loading delays, corrupted sd cards wouldn't be detected as quickly, and no way to deliver the translated manual.

There is no way we would introduce a more error-prone release like that when we finally have a more easy one to cut down on support efforts, sorry. Closing.

**Comment by jorgev259** [comment]
yeah because giving user a optional way to do it faster is bad. Tbh having to go through the patcher is annoying for me when i could just update my sd card files

**Comment by wabberz** [comment]
It's not like we have weekly releases. Putting the files on the sd card either via sd card reader, FTP or whatever you prefer takes like a minute. Patching takes 2-5 minutes depending on the speed of your sd-card and installing the resulting CIA takes seconds.

Sorry, for something you don't have to use that often I can't follow your reasoning that this is "annoying". It cut down on support requests by a lot, while LayeredFS was a great headache for us.

**Comment by jorgev259** [comment]
why cant we have both?

**Comment by wabberz** [comment]
You are very insistent on something you rarely have to use. Is it possible you have other reasons for requesting a LayeredFS release?
I really, honestly can not follow your reasoning here and you are the first person to complain about the patcher, while everyone else has commended it.

**Comment by jorgev259** [comment]
because i like LayeredFS? i see no issue in having multiple options to use something

**Comment by wabberz** [comment]
You don't have to support it, that's why you probably can't understand that this will make supporting the patch more complicated. The answer is no.

**Comment by jorgev259** [comment]
may i present to you any 3ds pokemon mod on earth?

**Comment by wabberz** [comment]
I'm not risking litigation and the possible cancellation of this project for this. Your argument does not make sense to me and there is no way that we would release the the files just like that. You would still need to use a patcher to make them.

But is this the reason you want the LayeredFS files? You want to make mods?

**Comment by jorgev259** [comment]
no, i just preffer using layeredfs than going the roundabout way

**Comment by wabberz** [comment]
I gave you plenty of reasons why we won't be doing that.
