### ISSUE TITLE
Requesting source code

### ISSUE THREAD

**Issue by noirscape** [ScarletStudy/DGS1-3DS-Release#46]
Given how the 3DS homebrew scene has had issues with both malware in the past (see: UnbanMii as a prime example) or developers who suddenly abandoned their tools or made worrisome statements after going closed source (Themely), I think it would be beneficial to have the source code available for the `.firm` file.

As a `.firm` file has the most permissions (NAND read/write coming in as a very obvious example) and is able to modify Horizon before it loads, I consider it to be highly important to be able to have access to the source code of these files, as there is potential for abuse here.

While I obviously am willing to assume that you have no bad intentions or would steep to this level of abuse, this is a concern that I can pretty safely say is not just shared by me, and I'd prefer to be safe over sorry.

**Comment by wabberz** [comment]
It's a GodMode9 firmrunner, so here you go: https://github.com/d0k3/GodMode9

**Comment by Hyarion-SS** [comment]
Understandable -- I had similar concerns, so this was developed with transparency in mind. All of my additions to the GodMode9 source for this patcher have been accepted upstream, making the autorun.gm9 script essentially the only addition.

That said, I'll fork the GM9 repo to allow you to build from the source yourself if you wish.

**Comment by noirscape** [comment]
@Hyarion-SS - Thanks, that would be very welcome.

**Comment by Hyarion-SS** [comment]
The source code for our fork is here -- https://github.com/ScarletStudy/DGS1-Patcher

**Comment by noirscape** [comment]
👍 Thanks a ton!
