### ISSUE TITLE
Episode 4 - Pat and the Police Handbook

### ISSUE THREAD

**Issue by DatXFire** [ScarletStudy/DGS1-3DS-Release#48]
I’m not sure where else to post this but I’m not sure if I found this portion of the game confusing due to a translation error or if I am missing out on a larger context within the game’s writing. When given the explanation as to why Pat moved the body, you use his Police Handbook as justification. My confusion arises as to concern with the two lines in the second page: “When he discovers an incident, the patrolman must lead the investigation.” & “If an incident occurs in a patrolman’s beat, he must assist in the initial investigation.”

In the case of the victim’s body, I don’t see the relevance as to where it was discovered being important. The first line would indicate that Pat would’ve had to lead the entire investigation for discovering the incident, regardless of whether it occurred in his beat. Am I misunderstanding, is this a plot hole within the game, or is there a translation error at work? Some clarification would be appreciated, and I apologize if this is not the proper place to bring this issue to light.

**Comment by Hyarion-SS** [comment]
You are correct -- it seems that these sentences got reversed somehow. The corrected translation reads:

> - If an incident occurs in a patrolman's beat, he must lead the investigation.
> - When he discovers an incident, the patrolman must assist in the initial investigation.

This has been fixed for our next release.

**Comment by DatXFire** [comment]
Good to hear! Thanks for all the hard work, I look forward to the rest of the game.
