### ISSUE TITLE
Possible formatting issue/typo on Case 2’s logbook

### ISSUE THREAD

**Issue by zaiman12345** [ScarletStudy/DGS1-3DS-Release#49]
I have an image, posted thru Discord and linked here: https://cdn.discordapp.com/attachments/484868986681688064/525779368279277603/image0.jpg
As you can see, there is an issue. Either the “Nothing unusual” (which should be “Nothing Unusual” with a capital U judging by what Sherlock says directly before giving you the evidence) is too long and pushing the times away, or the time slots aren’t spaced out enough. Either way, this kinda bugs me, even if it is a very small issue. The easy way to fix this, I assume, is to space out the empty time slots. Thanks in advance if you fix it!

**Comment by Hyarion-SS** [comment]
This was correctly spaced in our Episode 2 release -- it seems that the font changes in Episode 4 caused this. Sorry about that!

It's been fixed for our next release.
