### ISSUE TITLE
Episode 2 odd verb choice, possible typo

### ISSUE THREAD

**Issue by zaiman12345** [ScarletStudy/DGS1-3DS-Release#50]
In Sherlock’s second deduction segment, after the ship comes to an abrupt stop and Sherlock is found hanging on a clothing hook, he says “Last night, the snake, covered in speckles, sneaked through than entrance over there.” I’m not sure if this is a typo, since many sources say different things about this, but the sentence would flow better with snuck rather than sneaked.

**Comment by Hyarion-SS** [comment]
In our Ep2 release, we did in fact use "snuck" here. As it turns out, though, this is more of an Americanism, so we changed to "sneaked" when moving to British English.
