### ISSUE TITLE
Inconsistency in DGS1-2 and a weird 9 in DGS1-1

### ISSUE THREAD

**Issue by Superpcboy** [ScarletStudy/DGS1-3DS-Release#53]
Hi ScarletStudy, I decided to replay and I found some things. First thing, In the first episode I found this weird-ish 9. In the time it looks like the 9 is one font size smaller than the other numbers. 
![dgs 1209](https://user-images.githubusercontent.com/35067239/53658075-25c58100-3c58-11e9-8dd8-881ab614b48b.jpg)

Clearly the 9 don't touch the invisible bottom line. I don't know if this is normal, but felt worth mentioning.

Another thing that struck me, I've found in the second episode. The game continously tells me the Russian word гардероб means "Wardrobe". However when the Crime Scene Photo has been added to the Court Record, it states гардероб means "Closet". Since English isn't my first language, I don't really know whether or not this means the same. See pictures below.
![wardrobe](https://user-images.githubusercontent.com/35067239/53658554-61147f80-3c59-11e9-9a6b-af37a2b7f581.jpg)
![crime scene photo](https://user-images.githubusercontent.com/35067239/53658647-9faa3a00-3c59-11e9-90f5-dcb9ddcdb6ba.jpg)

Thank you very much for your time and all the work!

**Comment by Hyarion-SS** [comment]
The 9 has been bothering me as well - looks like a quirk of the font generator. I've manually fixed it.

As for "Closet", that's already been reported and fixed internally. Thanks for the report, though.

**Comment by Superpcboy** [comment]
Great to hear! In the final Theatre of Logic and Reason of case 2 you also have to present the 'Closet' (The one where you have to correct Nikomina about Asougi's intention), instead of 'Wardrobe'. Don't know if it's already fixed, but yet again I've found it worth to mention.
