### ISSUE TITLE
Case 1 Text Goes Off Screen in Profile Description

### ISSUE THREAD

**Issue by 1ted59** [ScarletStudy/DGS1-3DS-Release#54]
Viewable by scrolling to her profile in Case 1 after she is introduced.
![issue](https://user-images.githubusercontent.com/24933689/55285452-8977c280-535a-11e9-8d8b-44355ef5f6e4.png)

**Comment by keksdee** [comment]
s2g I mess one of these up every release. Fixing for the "things we messed up" release later on, thanks.
