### ISSUE TITLE
DGS1 Episode 1 typo

### ISSUE THREAD

**Issue by ClaudeNi** [ScarletStudy/DGS1-3DS-Release#55]
Asougi says "It take it late Doctor Watson didn't ingest anything, then?" When the first it should be an I

**Comment by ClaudeNi** [comment]
![20190331_205311](https://user-images.githubusercontent.com/49127719/55292911-e32eca00-53f8-11e9-82e6-56bba5aa6d66.jpg)
Here it is

**Comment by keksdee** [comment]
Fixed for next release, thanks

**Comment by DarkDengar** [comment]
Beat me to it!

> Asougi says "It take it late Doctor Watson didn't ingest anything, then?" When the first it should be an I

Beat me to it!
