### ISSUE TITLE
EP5 Wrong use of “then”

### ISSUE THREAD

**Issue by DatXFire** [ScarletStudy/DGS1-3DS-Release#58]
![BA8A66D2-24CD-49CF-A391-4E124CE9F3B4](https://user-images.githubusercontent.com/1962606/55310683-14c28800-542f-11e9-86f7-d1d7d4b2be92.jpeg)

I believe this should be “...*Than* when you realise you were right to trust them all along.”

During dialogue with Gina after you win her trial.

**Comment by keksdee** [comment]
Fixed for next release, thanks

**Comment by DatXFire** [comment]
Thanks! Some of the British English standards threw me for a bit, but glad I found this. Great work, looking forward to DGS 2.

(On an unrelated note I'm not sure why the image appears upside down, clicking on it shows the image is oriented correctly and it also appears right side up on my phone, but upside down on my desktop web browsers.)
