### ISSUE TITLE
Case 1-Beginning Grammatical Ambiguity

### ISSUE THREAD

**Issue by PixelSergey** [ScarletStudy/DGS1-3DS-Release#60]
![image](https://user-images.githubusercontent.com/14542417/55349794-3ec58a00-54c3-11e9-8bcf-cb5ae17b9b38.png)
In the beginning of case 1:

Although the sentence can be read as such, the phrase "doctor's/doctors' notes" is often used as one concept instead of "a [specific] doctor's notes". Maybe consider rephrasing as "These appear to be doctors' notes." or a similar phrase?

**Comment by keksdee** [comment]
Modified for next release, thanks
