### ISSUE TITLE
"The minimum information necessary." Supposed to be "maximum"?

### ISSUE THREAD

**Issue by Wowfunhappy** [ScarletStudy/DGS1-3DS-Release#61]
It's my first time playing through this episode.

In Episode 4, Gregson gives Naruhodou a map of the crime scene. Naruhodou seems quite grateful, saying:
> Wow! You'd give this to us?

Gregson responds:

> It's our policy to give the culprit's attorney the **minimum** information necessary.

Is this supposed to say "maximum"? "Minimum" doesn't make sense in context, unless it's supposed to be some kind of joke?

**Comment by keksdee** [comment]
Yeah, it's meant to be a joke. Like, they don't like defense attorneys, so they give them _only_ the minimum.

**Comment by Wowfunhappy** [comment]
Ah, okay, sorry for the false report. I do wonder if it could be made a bit clearer, as it wasn't obvious to me—but maybe that's how it was in the original script. *shrug*
