### ISSUE TITLE
Chapter 5 trial inconsistency

### ISSUE THREAD

**Issue by ToonLucas22** [ScarletStudy/DGS1-3DS-Release#63]
Just finished playing the final chapter; I enjoyed it a lot. But anyhow, I would like to report a few typos and inconsistencies I found along the way (that weren't already reported, to my knowledge):

- ~~When Ryuunosuke and Susato check the stereoscope for the first time, Ryuu says "How about we it? Just a little." It's missing a word between "we" and "it".~~ (edit: already reported, oops)

- When Ryuunosuke discovers the presence of the second music box, shows it to the court and Chrogray reacts, his textbox name displays as _Benedict_, even though his real name had already been revealed long before that point.

**Comment by henke37** [comment]
The first is already reported as issue #57.

**Comment by keksdee** [comment]
Would you happen to remember any direct quotes from around the second issue? I'm brainfarting hard and I can't find this part of the script lol

**Comment by keksdee** [comment]
Alright, fixed for the next release. Thanks for that.

No idea why, but that's how it was in the original JP script? Bizarre.
