### ISSUE TITLE
Small typo in DGS2 demo

### ISSUE THREAD

**Issue by Superpcboy** [ScarletStudy/DGS1-3DS-Release#67]
While presenting Auchi as the victim. I found a small typo. It's about the word desparate (desperate). 
![15544932119771941128661](https://user-images.githubusercontent.com/35067239/55652306-6c744100-57eb-11e9-8b57-f40cc4569e5f.jpg)

**Comment by PixelSergey** [comment]
This issue should be filed in https://github.com/ScarletStudy/DGS2-3DS-Demo/issues, not here

**Comment by Superpcboy** [comment]
Whoops, didn't saw the new one. I'll file it there
