### ISSUE TITLE
Case 5 minor typo

### ISSUE THREAD

**Issue by WBSpitfire** [ScarletStudy/DGS1-3DS-Release#69]
~~Small typo in Juror 5's text when cross-examining Mr Chrogray.~~

![2019-04-07_10-45-51 048_top](https://user-images.githubusercontent.com/10167475/55687533-c297d000-5922-11e9-9ab5-842f0dc4b3b7.png)

~~Install is misspelled as instal. Sorry I didn't get a screenshot as it happened, only in backlog.~~

**Comment by keksdee** [comment]
It's a British English thing 👀

**Comment by WBSpitfire** [comment]
Huh... fair enough. Looked odd, and though I am aware of other British English uses in-game, I wasn't aware of instal/install. My bad.
