### ISSUE TITLE
Episode 4 - Pat and the Constable's Handbook (dialogue)

### ISSUE THREAD

**Issue by praabjerg** [ScarletStudy/DGS1-3DS-Release#70]
Issue #48 describes an issue where the meanings were reversed in the Constable's handbook in Episode 4. When I played the latest release (2.4.0), I noticed that while the *handbook* made sense, the *dialogue* referring to the handbook is reversed. It's been a couple of days since I played it, but as I recall, the dialogue uses the phrase "If an incident occurs in a patrolman’s beat, he must assist in the initial investigation."

But apart from that, thank you for a great translation effort! I am *so* happy to have finally been able to play this, and even happier to see just how good the translation was!

**Comment by keksdee** [comment]
Lord this handbook is gonna kill me. Fixed for next release, thanks.

**Comment by AdmiralCurtiss** [comment]
To ensure that is caught in both instances:

![2019-05-09_20-10-15 194_top](https://user-images.githubusercontent.com/4522237/57574896-0cebff80-7441-11e9-87b5-50f95cee0785.png)
![2019-05-09_20-10-03 473_top](https://user-images.githubusercontent.com/4522237/57574897-0e1d2c80-7441-11e9-828d-c3e19e45902d.png)
![2019-05-09_20-12-31 714_top](https://user-images.githubusercontent.com/4522237/57574901-14130d80-7441-11e9-80e0-24d2e38cde33.png)

Both of these lines should match the first line in the handbook.
