### ISSUE TITLE
Case 5 - Hatch's Revolver

### ISSUE THREAD

**Issue by interborough** [ScarletStudy/DGS1-3DS-Release#72]
Not sure if this has been reported before, but in case 5 when examining Hatch's revolver, it is said that the magazine is empty. This should instead say that "the cylinder is empty", or "the chamber is empty", since revolvers don't take magazines. Interestingly enough, the Tinpillar's revolver does this correctly, using the word chamber.

**Comment by keksdee** [comment]
Sick, thanks. Fixed for next release.
