### ISSUE TITLE
Case 4, orientation of the book the victim is grabbing?

### ISSUE THREAD

**Issue by praabjerg** [ScarletStudy/DGS1-3DS-Release#73]
Short explanation: In a closeup of the victim in case 4, she's holding a book that's supposed to have been burned (the exact title of the book eludes me now, but it was one of the Sherlock Holmes adventures).
If you examine the 3D model of the book in the court record, the burn is clearly visible at the top of the book, but in the closeup photo, the book looks perfectly fine, even though you're looking at it from the top. I actually thought this was going to turn out to be a contradiction in the trial, but it never came up, and they're clearly supposed to be the same book.
This could easily be an issue inherited from the original game, so I wasn't sure whether to bring it up. But I admire the way you seem to be shooting for something akin to perfection with this localisation, and I'm actually curious as to the origin of the issue:
What I *think* could have happened (if this is a result of the localisation), is that the title was originally written in Japanese, which would mean that to localise it properly, you may have had to flip the reading direction of the book, and thus the orientation of the title. So in the original game, maybe you were actually seeing the *bottom* of the book in the photo? But then you would have also had to change the orientation of the 3D model.
Is that it?... It feels like they could have had the title in English on the book, even in the original game. It was supposed to be an English book owned by a British character, after all.

The fact that I can't tell if this originates from the original game or the localisation is probably a testament to how much work you put into it. I continue to be fascinated and astonished by it!

**Comment by AdmiralCurtiss** [comment]
Yeah that was really bothering me too once I noticed it, it was never brought up. Here's the direct side-by-side:

![2019-05-10_16-12-15 251_top](https://user-images.githubusercontent.com/4522237/57574946-e1b5e000-7441-11e9-9a2d-a24164f48e42.png)
![2019-05-10_16-13-06 246_top](https://user-images.githubusercontent.com/4522237/57574947-e37fa380-7441-11e9-9511-e57349049a93.png)

**Comment by praabjerg** [comment]
You know, looking at it again, I feel pretty certain this must have been inherited from the original game. Holding the book like that, there's no way the burn *wouldn't* be visible. The cover is missing an entire corner on one side, after all. And the corners of both sides of the cover are visible in the photo.
Another remote possibility is that it's intentional, and turns out to be a clue to the larger mystery in DGS2. It's a bit of a stretch that the characters would have missed something this obvious in the court case, but I would still be absolutely delighted if it gets tied into the second game somehow :D

**Comment by Hyarion-SS** [comment]
As noted, this is in the original game -- the graphics here are unedited.

Thanks for the report, though.
