### ISSUE TITLE
Chapter 1, Trial 2: Asougi speaks twice

### ISSUE THREAD

**Issue by AquaBat** [ScarletStudy/DGS1-3DS-Release#74]
In the beginning of Part 2 (“Trial 2”) of Chapter 1, Asougi appears to refer to Naruhodou treating him to beef hot-pot at the cafeteria. But according to the name banners, Asougi apparently speaks both lines. I would assume this was just an error in translation, though it could very well be an error in the game itself.
https://imgur.com/a/CoPhcK9

**Comment by keksdee** [comment]
Fixed for next release, thanks
