### ISSUE TITLE
Chapter 5: Morse code

### ISSUE THREAD

**Issue by octopuserectus** [ScarletStudy/DGS1-3DS-Release#75]
Naruhodou:
‘Morse code is **comprised of** two sets of sounds’.

Even though the expression “comprised of" is not universally considered incorrect, I suggest you to consider changing “comprised of" to “comprises” or “composed of”. And revise any other instances of “comprised of” if they exist in the script and I missed them.

**Comment by darkkomdld** [comment]
I dont see the deal here. i most likely love comprised of than the other you say, i will answer you for respect to the translators.

**Comment by octopuserectus** [comment]
> 
> 
> I dont see the deal here.

“Comprise” already means “'consist of”.

**Comment by darkkomdld** [comment]
I think if it is with to be and with countable staff it´s not. It just works alone when connect sentences

**Comment by keksdee** [comment]
Sorry for taking so long to get back on this. Weird issue, but it's not like it takes a ton of effort to change it to "composed of," so why not? Fixed, thanks.
