### ISSUE TITLE
Episode 4 Souseki's room text formatting error

### ISSUE THREAD

**Issue by pentmo** [ScarletStudy/DGS1-3DS-Release#76]
When you are first able to go to Souseki's room (chapter 4 investigation 2), there is an accidental blank line where text should be. This occurs somewhere in one of Naruhoudo's text boxes during the chain of dialogue that appears upon examining the beckoning cat for the first time.

**Comment by keksdee** [comment]
Sorry for taking so long on this, fortunately this was fixed internally a while back here: https://github.com/ScarletStudy/DGS1-3DS-Release/issues/65

Thanks
