### ISSUE TITLE
Case 2 luma crash

### ISSUE THREAD

**Issue by marcchacon** [ScarletStudy/DGS1-3DS-Release#77]
Hello Scarlet Studio, I want to report a crash.
In case 2, luma crashes. It's possible that my Nintendo caused the problem, but I want to report it anyway.
I attach the images of the crash:
![P_20190417_195751_SRES](https://user-images.githubusercontent.com/15941876/56324278-b99ece00-616e-11e9-84a2-8f42dd190327.jpg)
![P_20190417_195820_SRES](https://user-images.githubusercontent.com/15941876/56324288-c0c5dc00-616e-11e9-8b15-d1fc8eebbb2d.jpg)

I hope that you can help me.

**Comment by wabberz** [comment]
This is a new one. Is this 2.4.0 downloaded from here and applied by yourself?

**Comment by marcchacon** [comment]
Yes, I downloaded yesterday

**Comment by wabberz** [comment]
OK, because it seems some people are merging the custom update we make into the main game to get the translated banner. This causes a lot of issues though. Did Luma3DS create a crash dump file? Also, which version of Luma3DS are you using?

**Comment by marcchacon** [comment]
No it didn't... Or at least I can't found it
I'm using 9.1

**Comment by wabberz** [comment]
It would be under `sd:/luma/dumps/`

**Comment by marcchacon** [comment]
Nothing...

**Comment by wabberz** [comment]
OK, this seems to be a crash of the game itself, not anything OS related. We'll try to find out what happened. Does this happen every time or only this one time?

**Comment by marcchacon** [comment]
Every time...
Also, sometimes crashes before, or after, but always in the same phrase. With after, I mean that loads the "y" but never finishes the phrase. I don't know if this can help to identify the problem.

**Comment by wabberz** [comment]
Do other games crash on this 3DS sometimes? You mentioned that you suspect it could be your 3DS.

**Comment by marcchacon** [comment]
No, only this game crashes.
I suspect of my 3ds because the sd was corrupted last year. I checked it and found nothing. Also crashes with other sd, so I discard the sd corruption option.

**Comment by wabberz** [comment]
OK, let's see if this is getting us somewhere:
can you hash these files for me using GodMode9 (A -> Calculate SHA-256)?
`sd:/3DS/ScarletStudy/DGS1-English-v2.4.0.cia`
`[A] SYSNAND SD > title/0004000e/0014ad00/content/00000000.app`

**Comment by marcchacon** [comment]
I always use "install and delete" so i can't do it in the original cia, I create a new one, no?

**Comment by wabberz** [comment]
The other one is probably enough anyways. I assume you are playing from a physical copy?

**Comment by marcchacon** [comment]
No, I download the Japanese version and apply the patch.

**Comment by wabberz** [comment]
So you're running this on a Japanese 3DS?

**Comment by marcchacon** [comment]
No, I have an EUR New 3ds.
I have no problems playing other regions games.

**Comment by wabberz** [comment]
Then I assume this is a pirated copy. Sorry, I cannot help you with that. You may be using a bad dump. I suggest you go legit.

**Comment by marcchacon** [comment]
Ok, thanks for all.
