### ISSUE TITLE
DGS 1 Case 3 typo

### ISSUE THREAD

**Issue by laptain** [ScarletStudy/DGS1-3DS-Release#78]
In Case 3 of DGS 1 the word 'biased' is spelt with two s (biassed).

This is spoken by Juror 6 when you find the contradiction in Gina's testimony.

Juror 6: "We shouldn't be biassed because she's a little thief."

**Comment by keksdee** [comment]
Sorry for taking so long to get back on this. It's a British English thing, see: https://dictionary.cambridge.org/us/dictionary/english/biassed

Thanks
