### ISSUE TITLE
Case 1: Text/Graphics inconsistency for Satoru Hosonaga's business card

### ISSUE THREAD

**Issue by AdmiralCurtiss** [ScarletStudy/DGS1-3DS-Release#79]
The graphics on his card say

Imperial Police
Satoru Hosonaga
First Squadron Investigation Leader
Detective

but Naruhodou reads "Imperial Police, Division 1: Investigation, Lead Detective, Satoru Hosonaga" on it when you examine the front for the first time. After you present this piece of evidence to the judge, Asougi reads "Imperial Police, Division 1: Investigation, Lead Detective Satoru Hosonaga" (note the lack of a comma after 'Detective'). Additionally, if you examine it again after that, Naruhodou reads "Imperial Police, First Squadron Investigation Leader, Detective Hosonaga".

These all should probably match eachother.

(3DS v2.4.0)

**Comment by keksdee** [comment]
Yyyyyyeah, someone edited the in-game text a while before release, but we forgot to fix the card itself. And also the re-read text too, I guess.

The text inconsistency has been fixed, looking into fixing up the graphic. Thanks.
