### ISSUE TITLE
Baseline of 'English' in the backlog is wrong

### ISSUE THREAD

**Issue by AdmiralCurtiss** [ScarletStudy/DGS1-3DS-Release#80]
This isn't really noticeably unless both 'English' and regular text are in the same box, but the baseline for the 'English' is way higher than the regular text, which looks pretty odd. It's not a huge deal really, but if it's an easy fix then might as well, right?

This only affects the backlog. The actual textboxes look fine.

![2019-04-27_14-09-58 321_top](https://user-images.githubusercontent.com/4522237/56851716-9adccc00-6912-11e9-9b1b-3de2b987863a.png)

(3DS v2.4.0)

**Comment by keksdee** [comment]
Sorry for taking so long to get back on this. This font has been such a bitch but we'll see if there's anything we can do about it, thanks.
