### ISSUE TITLE
Episode 3 wrong nametag on dialogue

### ISSUE THREAD

**Issue by Ichisuke83** [ScarletStudy/DGS1-3DS-Release#84]
On this dialogue Naruhodou get the name of Susato from her sentence about the elderly lady.
This happen during the closing argument in episode 3.

![2019-05-06_22-36-17 462_top](https://user-images.githubusercontent.com/50341633/57254361-5dceb300-7051-11e9-867b-8975bc4ec5c5.jpg)
![2019-05-06_22-36-33 399_top](https://user-images.githubusercontent.com/50341633/57254363-5dceb300-7051-11e9-9e93-0614c53dd757.jpg)
![2019-05-06_22-37-02 527_top](https://user-images.githubusercontent.com/50341633/57254364-5e674980-7051-11e9-9456-da971cd14c01.jpg)

It's also reflected on the log
![2019-05-06_22-38-17 149_top](https://user-images.githubusercontent.com/50341633/57254389-7048ec80-7051-11e9-9ef9-fbf9957867a3.jpg)

**Comment by henke37** [comment]
That's as it should be. She's speaking what he thinks. This is made clear right after those lines, if the quotes wasn't a big enough hint.

**Comment by Ichisuke83** [comment]
> That's as it should be. She's speaking what he thinks. This is made clear right after those lines, if the quotes wasn't a big enough hint.

Oh... so stupid.... just check and read that Susato then ask "Is that what you were thinking just now?" xD Sorry.... When playing it days ago I thought it was an error xD
