### ISSUE TITLE
Episode 5 double verb

### ISSUE THREAD

**Issue by Ichisuke83** [ScarletStudy/DGS1-3DS-Release#85]
Double "was"... maybe there was(lol) a "then" before pledged...?
![2019-05-03_21-03-13 025_top_right](https://user-images.githubusercontent.com/50341633/57254566-e8afad80-7051-11e9-8124-bfd525f86b4b.jpg)

**Comment by keksdee** [comment]
Kinda surprised nobody had mentioned this yet. Fixed, thanks.
