### ISSUE TITLE
Case 3: Minor text oddities

### ISSUE THREAD

**Issue by AdmiralCurtiss** [ScarletStudy/DGS1-3DS-Release#86]
![2019-04-29_18-38-42 779_top](https://user-images.githubusercontent.com/4522237/57574275-318eaa00-7436-11e9-88dd-2153d3bfce7a.png)

The 'himself' *just barely* fits into the provided space, which looks awkward. You may want to reformat this a bit.

---

![2019-04-30_08-30-20 391_top](https://user-images.githubusercontent.com/4522237/57574307-e45f0800-7436-11e9-93bb-6e1753278630.png)

Something feels wrong with Naruhodou's line here. It's playing on van Zieks' reference to vanishing into thin air, but with a pronoun of 'it' he's either implying that the killer is an object, or he's referring to the contradiction but in which case it doesn't make sense to say that it never showed up. I dunno.

**Comment by keksdee** [comment]
1. Frick, thanks
2. I guess a singular "they" would work here, even if it's gross. Fixed, thanks
