### ISSUE TITLE
Case 4: Text oddities

### ISSUE THREAD

**Issue by AdmiralCurtiss** [ScarletStudy/DGS1-3DS-Release#87]
![2019-05-04_20-11-55 702_top](https://user-images.githubusercontent.com/4522237/57574333-49b2f900-7437-11e9-96a7-f8d8b7a09238.png)

This is the first line of a conversation, but the way the line is written (with 'that man') makes it feel like it's supposed to follow something else, which makes it somewhat awkward to read.

---

![2019-05-04_20-19-43 970_top](https://user-images.githubusercontent.com/4522237/57574407-c09cc180-7438-11e9-83a3-4420ee1929aa.png)
![2019-05-04_20-19-12 634_top](https://user-images.githubusercontent.com/4522237/57574410-c72b3900-7438-11e9-8ff7-684a9c73bae1.png)

Something bothered me about that 'it' in 'never read any of it' when I made these screenshots, but rereading this I don't think it's actually so bad. I feel like it may flow slightly better if it was a 'them', clearly referring to the earlier mention of 'books', but I dunno, I'm fine either way I guess.

---

![2019-05-07_08-55-17 486_bot](https://user-images.githubusercontent.com/4522237/57574438-723bf280-7439-11e9-98b1-7f7a9cef2dcb.png)

That 'not' is too close to the edge of the textbox.

---

![2019-05-10_17-58-55 857_top](https://user-images.githubusercontent.com/4522237/57574802-10cb5200-7440-11e9-83c2-07326bb45ae2.png)

This is a consistency thing. I dunno how it is in Japanese, but you seem to have always typed these expressions from Souseki in ALL CAPS... except for this one.

---

![2019-05-08_17-35-36 824_top](https://user-images.githubusercontent.com/4522237/57574448-aca58f80-7439-11e9-987f-06429a3855a9.png)

This may be intentional, but how can they both be 'just married' and have a 1-year anniversary?

---

![2019-05-08_17-45-58 542_top](https://user-images.githubusercontent.com/4522237/57574455-ca72f480-7439-11e9-86c3-a35c288a3aa0.png)

In one (or maybe more?) of these boxes that are just like this one you can clearly hear the game printing a bunch of spaces if you let it print out slowly (and it takes a rather long time for it to reach the second part), and in others you can't. They should probably all act like the latter, without extra space printing sounds.

Also, all of them use the female speaker soundbyte even for the first half of the text, but I assume that's an engine limitation.

---

![2019-05-09_08-59-31 561_bot](https://user-images.githubusercontent.com/4522237/57574504-8f24f580-743a-11e9-992d-024a35842c93.png)

The "Trial 1 : Old Bailey" has an extra space in front of the colon.

---

Oh, and finally, why did you leave the Kokoro in the title of this case untranslated?

**Comment by keksdee** [comment]
1. Tidied up, thanks
2. Might as well "them" it, sure
3. Fixed, thanks
4. Fixed, thanks
5. A little reluctant to change this one, as it does the same thing in the JP. Maybe just call it Rola being dramatic.........?
6. God these are such a pain in the ass. I think I fixed the problem ones (likely related to our automatic spacing fixer putting the spaces behind the text speed control code), thanks. As for the feminine blips, yeah, there's not much we can do about that.
7. Fixed, thanks

8. Kokoro is a work by Souseki Natsume (and that's how it's known internationally as well, [see here](https://en.wikipedia.org/wiki/Kokoro), so we figured it was more appropriate to leave it as such.
