### ISSUE TITLE
Case 4: Susato's bad grammar

### ISSUE THREAD

**Issue by PixelSergey** [ScarletStudy/DGS1-3DS-Release#89]
I'm loath to admit -> I'm loathing to admit.
Even with that fix, the whole sentence seems very much off. Maybe consider rephrasing that entire text box?

![image](https://user-images.githubusercontent.com/14542417/57582271-41a49900-74cb-11e9-9964-e821cbb6857a.png)

**Comment by keksdee** [comment]
https://en.oxforddictionaries.com/definition/loath

I'll get to the other issues when I'm not busy with stuff

**Comment by PixelSergey** [comment]
Of course, no hurry
