### ISSUE TITLE
Case 4: Receipt

### ISSUE THREAD

**Issue by PixelSergey** [ScarletStudy/DGS1-3DS-Release#90]
![image](https://user-images.githubusercontent.com/14542417/57582390-f55a5880-74cc-11e9-8400-2e2ea8ba280c.png)

"Pennies" is supposed to be abbreviated as "d.", as opposed to simply "d".
From what research I did, the British used a "raised decimal point" (·) to separate decimals and units, as opposed to the comma used in continental Europe. Is this correct?
Also, in general, the lines and the "Two shillings received in payment" text look very much off. Is it at all possible to remake this (perhaps using images instead of simple text)?

**Comment by keksdee** [comment]
Probably going to remove the line break near the bottom or something to make it all fit in the frame, will consider the raised decimal. I'll mark it as fixed internally when it actually happens.
