### ISSUE TITLE
Wording: T(h)-Thanks?

### ISSUE THREAD

**Issue by Hopiless** [ScarletStudy/DGS1-3DS-Release#91]
![56865902-988e7680-69d3-11e9-9b2d-92237dca3a49 1](https://user-images.githubusercontent.com/50633931/57718013-43886c80-7631-11e9-9b04-09c63fac211f.png)

This is probably me not being used to it and intended by the translation team but I usually I see an h after T in T(h)-Thanks. Not an issue to me personally but maybe something to bring up.  

Also I'm recycling this image from a different post here for a quality image example.

**Comment by keksdee** [comment]
~~I don't like it myself, but~~ the group voted a while back for always using single-letter stutters, rather than the whole sound. Thanks tho
