### ISSUE TITLE
Case 5: Text oddities.

### ISSUE THREAD

**Issue by AdmiralCurtiss** [ScarletStudy/DGS1-3DS-Release#93]
![2019-05-12_14-15-49 328_top](https://user-images.githubusercontent.com/4522237/58199111-12163d80-7cd0-11e9-9a8d-4c0dc2948031.png)

If the font supports it, consider using the 'ç ' for façade here.

---

![2019-05-12_14-19-31 067_top](https://user-images.githubusercontent.com/4522237/58199215-4a1d8080-7cd0-11e9-806c-1d6d1b59deeb.png)

This feels like an awkward first line in a conversation to me. I'd expect something like 'You have proof that the pledge...' or something along those lines, I forget the exact context.

---

![2019-05-12_14-26-08 592_bot](https://user-images.githubusercontent.com/4522237/58199307-805b0000-7cd0-11e9-80e0-160743a1b773.png)
![2019-05-19_22-35-26 733_bot](https://user-images.githubusercontent.com/4522237/58199318-87820e00-7cd0-11e9-8fa4-e0ed9e4c75d5.png)
![2019-05-19_22-35-40 345_bot](https://user-images.githubusercontent.com/4522237/58199326-894bd180-7cd0-11e9-95d5-8e95ef6594aa.png)
![2019-05-20_19-14-24 479_bot](https://user-images.githubusercontent.com/4522237/58199334-8bae2b80-7cd0-11e9-943b-e94e2ff0d353.png)

The top line in all of these gets uncomfortably close to the right edge of the box. Just move the linebreak.

---

![2019-05-13_19-19-49 947_top](https://user-images.githubusercontent.com/4522237/58200065-2d824800-7cd2-11e9-81ad-79a1d980e0ba.png)

The first line from Susato here feels like it's missing a word or something.

---

![2019-05-13_19-20-50 941_top](https://user-images.githubusercontent.com/4522237/58200192-7e923c00-7cd2-11e9-8fcc-43c1538bce26.png)

I feel like Susato would put a 'Mr' in front of Mortar here.

---

![2019-05-19_10-14-27 674_top](https://user-images.githubusercontent.com/4522237/58199600-1db63400-7cd1-11e9-83db-8a129f5700da.png)

'Van' in 'Lord Van Zieks' should be lowercase to match the rest of the game.

---

![2019-05-19_12-45-44 524_bot](https://user-images.githubusercontent.com/4522237/58199634-332b5e00-7cd1-11e9-9ac9-22366a2f070f.png)

Extra space between Trial 1 and the colon, like in case 4.

---

![2019-05-20_19-10-07 295_top](https://user-images.githubusercontent.com/4522237/58200275-bb5e3300-7cd2-11e9-9ffa-ea97e499ecff.png)

Is that intentionally a past tense 'led'? I was under the impression he's still working at the company.

---

![2019-05-21_08-37-20 012_top](https://user-images.githubusercontent.com/4522237/58199957-e85e1600-7cd1-11e9-8bbd-fa39d802c2ee.png)

Should be 'than', not 'then'.

---

![2019-05-21_09-16-53 735_top](https://user-images.githubusercontent.com/4522237/58199987-f90e8c00-7cd1-11e9-85c1-47080be2e979.png)

Untranslated post-credits screen.

**Comment by keksdee** [comment]
1. Tbh I didn't know ç was in our font but it looks like it is, thanks
2. Fixed, thanks
3. Fixed, thanks; the smaller text box on these is always such a pain
4. I think this line works better spoken out loud, but since not everyone is going to do that, *fixed thanks*
5. Sure Why Not™, fixed
6. I don't who in fuck did this but I'm mad, *fixed thanks*
7. Just fixed this in the other issue, thanks
8. Fair Enough™, fixed
9. Looks like it's been fixed already, thanks
10. From another (later) issue: ```About 8.: This is the title of the game and the big kanji means "The End". This is translated in the Android version, since we had to re-encode the credits video for that anyways, but for 3DS we figured it wasn't that important to justify re-encoding the video with a loss in quality and bloating the patch size..```
