### ISSUE TITLE
Case 4: Minor Text Formatting Error

### ISSUE THREAD

**Issue by MadsInZero** [ScarletStudy/DGS1-3DS-Release#94]
![IMG_0641](https://user-images.githubusercontent.com/38944027/58364781-b5e43100-7efc-11e9-8c4b-01fc772cd7ba.jpg)

In Chapter 4: The Clouded Kokoro, there's this minor line-break error when examining the beckoning cat in Souseki's room. This happens even when re-examining the item.

**Comment by keksdee** [comment]
Fixed in a previous issue, thanks tho
