### ISSUE TITLE
Case 5: Typo or deliberate?

### ISSUE THREAD

**Issue by PixelSergey** [ScarletStudy/DGS1-3DS-Release#96]
In multiple places in the case 5 investigations 1-4, the hospital Holmes is brought to is referred to as the "St Andrewd Hospital."

![image](https://user-images.githubusercontent.com/14542417/58386523-a6064300-8009-11e9-9a9a-238a356c4904.png) ![image](https://user-images.githubusercontent.com/14542417/58386524-a8689d00-8009-11e9-85a9-9b9dc099735b.png) ![image](https://user-images.githubusercontent.com/14542417/58386526-aacaf700-8009-11e9-86bd-c7d63f43670d.png) ![image](https://user-images.githubusercontent.com/14542417/58386527-ad2d5100-8009-11e9-8655-b7be10edb2b5.png)

This sticks out like a sore thumb. 
After googling around to verify, no such hospital exists. The obvious name that it should be is "St Andrew's Hospital," which was (and is) a real place in London.
Why was this choice made?

**Comment by wabberz** [comment]
Because the Japanese name is アントルード病院 - so St. Andrew's doesn't work. We figured the hospital is not real.

**Comment by keksdee** [comment]
The game doesn't reference a real hospital. The hospital in the game is not real.

**Comment by PixelSergey** [comment]
Sorry to pick this up again, but wouldn't a more fitting, English sounding name be better? If not Andrew's, then maybe Untrode or Untorde, which is the direct Google Translation? Again, Andrewd is so unnatural-sounding that it feels like a typo or horrible misunderstanding.

**Comment by SoaringChris** [comment]
It's honestly probably a pun on Andrews and rude
