### ISSUE TITLE
Case 5: Double-conditional

### ISSUE THREAD

**Issue by PixelSergey** [ScarletStudy/DGS1-3DS-Release#97]
![image](https://user-images.githubusercontent.com/14542417/58386548-02696280-800a-11e9-9afc-8eb2078085b1.png)

"I should **probably** give it a proper name, **I guess**." Two conditionals in the same sentence is a bit redundant.

**Comment by keksdee** [comment]
I think it's fine considering it's an uncertain statement, but I have an idea for a rewrite anyway 👀
