### ISSUE TITLE
Case 1: Asougi's headband - Suggest replacing "frilly" with "flashy"

### ISSUE THREAD

**Issue by whiskeyii01** [ScarletStudy/DGS1-3DS-Release#99]
In Case 1 (Trial 2, maybe?) Asougi makes a quip about Naruhoudo being dressed in all black, to which Naruhoudo mentally replies that Asougi "would be dressed in all black too, if it weren't for that frilly headband". I think "flashy" would be a better substitute for "frilly", as there's nothing "frilly" about the headband, and I think flashy better conveys that it's a conspicuous piece of clothing that really stands out.

**Comment by keksdee** [comment]
Tru™, fixed thanks
